# ===================================================================
# JawnzGateway Staging Spring Cloud Config.
# ===================================================================

# Mongo Atlas connection properties
spring:  
  data:
    mongodb:
      uri: 'mongodb+srv://admin:{cipher}83b93ebb0869398022304af0d2703bb7d9d1692778a56d7a1232f9a564c0cd0c944b9d3c58af39ef71c609eab715ad13cluster0.z3m9l.mongodb.net/jawnzgateway?retryWrites=true&w=majority' #mongodb://localhost:27017
      database: jawnzgateway
    jest:
      uri: ${BONSAI_URL}
  elasticsearch:
    rest:
      uris: https://juniper-549921985.eu-west-1.bonsaisearch.net:443
      read-timeout: 10000
      username: '{cipher}c0764576347771a7113622c0d8de3abf4e5937e17dd368167312406617cf3521'
      password: '{cipher}400d49eacfc022666bc7a160a0b6b6c090ede0ff90ca89f2daa01f7df1bdec5f'