# ===================================================================
# JawnzBack Staging Spring Cloud Config.
# ===================================================================

eureka:
  instance:
    hostname: jawnzback.herokuapp.com
    non-secure-port: 80
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: ${JHIPSTER_REGISTRY_URL}/eureka/
        
spring:  
  data:
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: prod
    url: jdbc:${JDBC_DATABASE_URL}
    user: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  r2dbc:
    url: r2dbc:${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}  
  elasticsearch:
    uris: ${ELASTIC_URL}
  cloud:
    stream:
      kafka:
        binder:
          replicationFactor: 3
          auto-create-topics: true
          brokers: pkc-4r297.europe-west1.gcp.confluent.cloud:9092
          configuration:
            security:
              protocol: SASL_SSL
            sasl:
              mechanism: PLAIN
              jaas:
                config: org.apache.kafka.common.security.plain.PlainLoginModule required username="FNS2CFI7N5OUQ4HD" password="hAwCuCn1honn54XentUm6BvxMPLIUfzGcCoT3HOKakQqPnoNfTzMTmy+Uzv7TSP6";
      bindings:
        binding-in-sse:
          destination: sse-topic
          content-type: text/plain
          group: jawnzback
        binding-out-sse:
          destination: sse-topic
          content-type: text/plain
          group: jawnzback
    

server:
  port: ${PORT:8080}
              
logging:
  level:
    ROOT: INFO
    org.apache.kafka.clients: OFF