# ===================================================================
# JawnzBack Staging Spring Cloud Config.
# ===================================================================

eureka:
  instance:
    hostname: jawnzback.herokuapp.com
    non-secure-port: 80
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: ${JHIPSTER_REGISTRY_URL}/eureka/

jhipster:
  cache:
    memcached:
      enabled: true
      servers: ${MEMCACHIER_SERVERS}
      expiration: 300
      use-binary-protocol: true
      authentication:
        enabled: true
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}
        
spring:  
  data:
    mongodb:
      uri: '{cipher}94bae20b506c783915a5d64b7b521102694bd017eca7a2b3cd8b0273e15d67b4a713dac885610d2848887ea78c2f0a5d380a6042dfa85d50abdf4fbbebe702a8eb2430aeaef65540cbb120f297261e5f456b7e3aecc92b9b783f71ff5379688869d12709c880c19da2aa727904171ad6' #mongodb://localhost:27017
      database: jawnzback
  elasticsearch:
    uris: ${ELASTIC_URL}
  cloud:
    stream:
      kafka:
        binder:
          replicationFactor: 3
          auto-create-topics: true
          brokers: pkc-4r297.europe-west1.gcp.confluent.cloud:9092
          configuration:
            security:
              protocol: SASL_SSL
            sasl:
              mechanism: PLAIN
              jaas:
                config: org.apache.kafka.common.security.plain.PlainLoginModule required username="FNS2CFI7N5OUQ4HD" password="hAwCuCn1honn54XentUm6BvxMPLIUfzGcCoT3HOKakQqPnoNfTzMTmy+Uzv7TSP6";
      bindings:
        binding-in-sse:
          destination: sse-topic
          content-type: text/plain
          group: jawnzback
        binding-out-sse:
          destination: sse-topic
          content-type: text/plain
          group: jawnzback
    

server:
  port: ${PORT:8080}
              
logging:
  level:
    ROOT: INFO
    org.apache.kafka.clients: OFF