# ===================================================================
# JawnzGateway Staging Spring Cloud Config.
# ===================================================================

# Mongo Atlas connection properties
spring:  
  data:
    mongodb:
      uri: mongodb+srv://admin:Password1@cluster0.z3m9l.mongodb.net/jawnzgateway?retryWrites=true&w=majority #mongodb://localhost:27017
      database: jawnzgateway
    jest:
      uri: ${BONSAI_URL}
  elasticsearch:
    rest:
      uris: https://juniper-549921985.eu-west-1.bonsaisearch.net:443
      read-timeout: 10000
      username: '{cipher}sbhgtpn0vh'
      password: '{cipher}bgye1a8l9k'