# ===================================================================
# JawnzGateway Staging Spring Cloud Config.
# ===================================================================

eureka:
  instance:
    hostname: jawnzgateway.herokuapp.com
    non-secure-port: 80
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: ${JHIPSTER_REGISTRY_URL}/eureka/
      
jhipster:
  cache:
    memcached:
      enabled: true
      servers: ${MEMCACHIER_SERVERS}
      expiration: 300
      use-binary-protocol: true
      authentication:
        enabled: true
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}      
      
spring:  
  data:
    mongodb:
      uri: '{cipher}b638b841f3cd39669cb3ce8d1287815d88be31b652d6a19c5d220d6d1b25d1d57efa0b9f3c68e5847827e67ec99bc3e41fe8898d6e39ea570434cc72918358d8eaf2aa4085384eaa94b398488d4fd3f4cc4c3a663dd73cd60ea6b017a4fef16c0c3803a30078068c3c0250b8aad357246d894e8aac44206128174a3b0d7415ed' #mongodb://localhost:27017
      database: jawnzgateway
            
logging:
  level:
    ROOT: INFO
    org.apache.kafka.clients: OFF
            