# ===================================================================
# JawnzGateway Staging Spring Cloud Config.
# ===================================================================

eureka:
  instance:
    hostname: jawnzgateway.herokuapp.com
    non-secure-port: 80
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: ${JHIPSTER_REGISTRY_URL}/eureka/
      
spring:
  data:
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: prod
    url: jdbc:${JDBC_DATABASE_URL}
    user: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  r2dbc:
    url: r2dbc:${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}  
  elasticsearch:
    uris: ${ELASTIC_URL}

server:
  port: ${PORT:8080}
              
logging:
  level:
    ROOT: INFO
            